In [1]:
# Import libraries
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import numpy as np
import tensorflow as tf

/Users/camillereyes/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
a = tf.constant(3.0, dtype=tf.float32)
b = tf.constant(4.0) # also tf.float32 implicitly
total = a + b

In [3]:
print(a)
print(b)
print(total)

Tensor("Const:0", shape=(), dtype=float32)
Tensor("Const_1:0", shape=(), dtype=float32)
Tensor("add:0", shape=(), dtype=float32)


In [4]:
# Session
sess = tf.Session()
print(sess.run(total))

7.0


In [5]:
# Run
print(sess.run({'ab':(a, b), 'total':total}))

{'ab': (3.0, 4.0), 'total': 7.0}


In [6]:
# Creating random vector
vec = tf.random_uniform(shape=(3,))
out1 = vec + 1
out2 = vec + 2

In [7]:
print(sess.run(vec))
print(sess.run(vec))
print(sess.run((out1, out2)))

[0.40537906 0.97670007 0.9764689 ]
[0.36854112 0.10354829 0.41445827]
(array([1.822891 , 1.3258533, 1.5696824], dtype=float32), array([2.822891 , 2.3258533, 2.5696824], dtype=float32))


In [8]:
# Placeholder
x = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)
z = x + y

In [9]:
# feed_dict: to feed concrete values to the placeholders
print(sess.run(z, feed_dict={x: 3, y: 4.5}))
print(sess.run(z, feed_dict={x: [1, 3], y: [2, 4]}))

7.5
[3. 7.]


In [10]:
my_data = [
            [0, 1,],
            [2, 3,],
            [4, 5,],
            [6, 7,],
          ]

In [11]:
slices = tf.data.Dataset.from_tensor_slices(my_data)
next_item = slices.make_one_shot_iterator().get_next()

In [12]:
while True:
  try:
    print(sess.run(next_item))
  except tf.errors.OutOfRangeError:
    break

[0 1]
[2 3]
[4 5]
[6 7]


In [13]:
# Initializing the iterator
r = tf.random_normal([10,3])
dataset = tf.data.Dataset.from_tensor_slices(r)
iterator = dataset.make_initializable_iterator()
next_row = iterator.get_next()

In [14]:
sess.run(iterator.initializer)
while True:
  try:
    print(sess.run(next_row))
  except tf.errors.OutOfRangeError:
    break

[ 0.28555787  0.5375323  -0.33698943]
[ 0.6827644  -0.12785766 -0.69622326]
[ 1.4645908  -0.15434271 -1.7112454 ]
[-0.5657453   0.12035253  0.68487126]
[ 1.3362097  0.4790712 -2.224063 ]
[-0.2923087   0.98731077  0.8751796 ]
[-3.0948353  -0.26624292 -0.2277559 ]
[ 0.05794363 -0.70698625 -1.3515084 ]
[0.66615003 1.6299336  1.5118786 ]
[-0.04107268  1.8482515  -0.4051471 ]


In [15]:
# Creating layers
x = tf.placeholder(tf.float32, shape=[None, 3])
linear_model = tf.layers.Dense(units=1)
y = linear_model(x)

In [16]:
# Initializing layers
init = tf.global_variables_initializer()
sess.run(init)

In [17]:
sess.run(y, {x: [[1, 2, 3],[4, 5, 6]]})

array([[ -4.0701246],
       [-10.095268 ]], dtype=float32)

In [18]:
# Layer function shortcuts
x = tf.placeholder(tf.float32, shape=[None, 3])
y = tf.layers.dense(x, units=1)

In [19]:
init = tf.global_variables_initializer()
sess.run(init)

In [20]:
sess.run(y, {x: [[1, 2, 3], [4, 5, 6]]})

array([[1.1711851],
       [4.2816057]], dtype=float32)

In [21]:
# Feature columns 
features = {
    'sales' : [[5], [10], [8], [9]],
    'department': ['sports', 'sports', 'gardening', 'gardening']}

In [22]:
department_column = tf.feature_column.categorical_column_with_vocabulary_list(
        'department', ['sports', 'gardening'])

In [23]:
department_column = tf.feature_column.indicator_column(department_column)

In [24]:
columns = [tf.feature_column.numeric_column('sales'), department_column]

In [25]:
inputs = tf.feature_column.input_layer(features, columns)

In [26]:
var_init = tf.global_variables_initializer()
table_init = tf.tables_initializer()
sess = tf.Session()
sess.run((var_init, table_init))

(None, None)

In [27]:
sess.run(inputs)

array([[ 1.,  0.,  5.],
       [ 1.,  0., 10.],
       [ 0.,  1.,  8.],
       [ 0.,  1.,  9.]], dtype=float32)